ITIExaminationSyustem/Models/StudentCourses.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ITIExaminationSyustem.Models
{
    public class StudentCourses
    {
        [ForeignKey("Navigation_Student")]
        public int? Std_Id { get; set; }
        [ForeignKey("Navigation_Course")]
        public int? Crs_Id { get; set; }
        public int Grade { get; set; }

        #region Navigation property
        public Course Navigation_Course { get; set; }
        public Student Navigation_Student { get; set; }
        #endregion
    }
}

ITIExaminationSyustem/Controllers/ExamController.cs
using ITIExaminationSyustem.Interfaces;
using ITIExaminationSyustem.Models;
using ITIExaminationSyustem.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace ITIExaminationSyustem.Controllers
{
    [Authorize]
    public class ExamController : Controller
    {
        IExamRepo _examRepo;
        IQuestionRepo _questionRepo;
        IChoiceRepo _choiceRepo;
        IExamQuestionRepo _examQuestionRepo;
        IStudentCourseRepo _studentCourseRepo;
        public ExamController(IExamRepo examRepo, IQuestionRepo questionRepo, IChoiceRepo choiceRepo, IExamQuestionRepo examQuestionRepo, IStudentCourseRepo studentCourseRepo)
        {
            _examRepo = examRepo;
            _questionRepo = questionRepo;
            _choiceRepo = choiceRepo;
            _examQuestionRepo = examQuestionRepo;
            _studentCourseRepo = studentCourseRepo;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TakeExam(int? crsId, int? stdId)
        {
            if(crsId == null || stdId == null)
            {
                return BadRequest();
            }
            else
            {
                StudentCourse studentCourse = _studentCourseRepo.GetByIds(crsId.Value, stdId.Value);
                if(studentCourse == null)
                {
                    return NotFound();
                }
                else
                {
                    List<ExamQs> examQuestions = _examQuestionRepo.GenerateExam(crsId.Value, stdId.Value);
                    return View(examQuestions);
                }
            }
        }

        [HttpPost]
        public IActionResult TakeExam(int examId, Dictionary<int,string> questions)
        {
            foreach(var question in questions)
            {
                ExamQs examQs = _examQuestionRepo.GetByIds(examId, question.Key);
                examQs.Student_Answer = question.Value;
                _examQuestionRepo.CheckAnswer(examQs);
            }


            return RedirectToAction("Index","Home");

        }

        public IActionResult DisplayExamTemplate(int? examId, bool? isAnswered)
        {
            if (examId == null || isAnswered == null)
            {
                return BadRequest();
            }
            else
            {
                Exam exam = _examRepo.GetById(examId.Value);
                if (exam == null)
                {
                    return NotFound();
                }
                else
                {
                    ViewBag.Answered = isAnswered;
                    List<ExamQs> examQuestions = _examQuestionRepo.GetExamQuestions(examId.Value);
                    return View(examQuestions);
                }
            }
        }
    }
}

ITIExaminationSyustem/Controllers/StudentController.cs
using ITIExaminationSyustem.Interfaces;
using ITIExaminationSyustem.Models;
using ITIExaminationSyustem.ViewModels;
using ITIExaminationSyustem.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace ITIExaminationSyustem.Controllers
{
    [Authorize]
    
    public class StudentController : Controller
    {
        private IStudentRepo _studentRepo;
        private IDepartmentRepo _departmentRepo;
        private IMainDeptRepo _mainDeptRepo;
        private ICourseRepo _courseRepo;
        private IStudentCourseRepo _studentCourseRepo;
        private IUserRepo _userRepo;
        private IBranchRepo _branchRepo;
        private IExamRepo _examRepo;
        private Exam_Context _context;
        public StudentController(IBranchRepo branchRepo,IStudentRepo studentRepo, IDepartmentRepo departmentRepo, IMainDeptRepo mainDeptRepo, ICourseRepo courseRepo, IStudentCourseRepo studentCourseRepo, Exam_Context context, IUserRepo userRepo, IExamRepo examRepo)
        {
            _studentRepo = studentRepo;
            _departmentRepo = departmentRepo;
            _mainDeptRepo = mainDeptRepo;
            _courseRepo = courseRepo;
            _studentCourseRepo = studentCourseRepo;
            _context = context;
            _userRepo = userRepo;
            _branchRepo = branchRepo;
            _examRepo = examRepo;
        }
        public IActionResult Index()
        {
            var StudentList = _studentRepo.GetAll();
            
            return View(StudentList);
        }
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            else
            {
                Student student = _studentRepo.GetById(id.Value);
                if (student == null)
                {
                    return NotFound();
                }
                else
                {
                    return View(student);
                }
            }
        }

        public IActionResult StudentCourses(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            else
            {
                Student student = _studentRepo.GetById(id.Value);
                if (student == null)
                {
                    return NotFound();
                }
                else
                {
                    ViewBag.ExamsList = _examRepo.GetAll();
                    return View(student);
                }
            }
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            StudentDepartmentsViewModel studentdepartment= new StudentDepartmentsViewModel();
            var student = _studentRepo.GetById(id.Value);
            if (student == null)
            {
                return NotFound();
            }
            
           
            var allCoursesInStudentDepartment = _departmentRepo.GetCourses(student.Dept_Id.Value);
            
            //department

            var branchId = student.Navigation_Department.Brch_Id;
           
            var departmentsInBranch = _departmentRepo.GetDepartmentsByBranchId(branchId.Value);


            studentdepartment.MainDepartmentsInStudentBranch = departmentsInBranch.Select(a=>a.Navigation_MainDepartment).ToList();

        //-----------------------------------------------------------------------------------------------------------------------------------
            studentdepartment.Student_Name = student.Navigation_User?.User_Name;
            studentdepartment.Student_Email = student.Navigation_User?.User_Email;
            studentdepartment.Student_DepartmentName = student.Navigation_Department?.Navigation_MainDepartment?.MainDepartment_Name;
            studentdepartment.StudentCourses = _studentCourseRepo.GetStudentCourses(id.Value);
            studentdepartment.Student_Image = student.Navigation_User?.User_Image;
            ViewBag.CoursesNotInStudent = allCoursesInStudentDepartment.Except(studentdepartment.StudentCourses);
            return View(studentdepartment);
        }

        [HttpPost]
        async public Task<IActionResult> Edit(int id,IFormFile image,List<int> toAdd, List<int> toRemove, StudentDepartmentsViewModel studentDepartmentsViewModel)
        {
            if (ModelState.IsValid)
            {
                var student = _studentRepo.GetById(id);
                if(student == null)
                {
                    return NotFound();
                }
                // handle courses
                foreach (var item in toAdd)
                {
                    var studentCourse = new StudentCourse {Std_Id=id,Crs_Id=item,Bonus=0 };
                    student.Navigation_StudentCourses.Add(studentCourse);
                }
                _context.SaveChanges();
                foreach (var item in toRemove)
                {
                    var studentCourse = _studentCourseRepo.GetStudentCourseDetails(id, item);
                    student.Navigation_StudentCourses.Remove(studentCourse);
                }
                _context.SaveChanges();
                // handle department
                var branchId = student.Navigation_Department.Brch_Id;
                var mainDepartmentId = studentDepartmentsViewModel.Student_DepartmentNumber; //main dep
                var newDepartment = _departmentRepo.GetDepartmentsByBranchId(branchId.Value).FirstOrDefault(a => a.MainDept_Id == mainDepartmentId);
                student.Dept_Id = newDepartment.Department_Id;
                _context.SaveChanges();
                //--------------------------------------------------
                student.Navigation_User.User_Email = studentDepartmentsViewModel.Student_Email;
                student.Navigation_User.User_Name = studentDepartmentsViewModel.Student_Name;
                _context.SaveChanges();
                //update image
                if (image != null)
                {
                    string fileExt = image.FileName.Split('.').Last();
                    string imagePath = $"wwwroot/Images/img-{student.Student_Id}.{fileExt}";
                    using (var fs = new FileStream(imagePath, FileMode.Create)) // make this line used inside the brackets and then disposed
                    {
                        await image.CopyToAsync(fs);
                    }
                    student.Navigation_User.User_Image = $"/Images/img-{student.Student_Id}.{fileExt}";
                    _context.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            else
            {
                string errorMessage = "";
                foreach (var modelStateValue in ModelState.Values)
                {
                    foreach (var error in modelStateValue.Errors)
                    {
                        // Log or debug the error messages
                        errorMessage += error.ErrorMessage;
                    }
                }
                ViewBag.errs = errorMessage;
                return View(studentDepartmentsViewModel);

            }
        }

        [HttpGet]
        public IActionResult Add() // user
        {
            ViewBag.Users = _userRepo.GetNonAssignedUsers();
            var branches = _branchRepo.GetAll();
            return View(branches);

        }
        [HttpGet]
        public IActionResult AddToBranch(int? branchId,int? userId) // branch id
        {
            if(branchId == null || userId == null)
            {
                return BadRequest();
            }
            var mainDepartments = _departmentRepo.GetDepartmentsByBranchId(branchId.Value).Select(a=>a.Navigation_MainDepartment).ToList();
           
            TempData["BranchId"] = branchId;
            TempData["UserId"] = userId.Value;
            return View(mainDepartments);
        }

        [HttpPost]
        public IActionResult AddToBranch(AddStudentViewModel addStudentViewModel)
        {
            if(ModelState.IsValid)
            {
                int? branchId;
                int? userId;

                branchId = (int)TempData["BranchId"];
                userId = (int)TempData["UserId"];
                if(branchId == null || userId == null)
                {
                    return BadRequest();
                }
                var department = _departmentRepo.GetDepartmentsByBranchId(branchId.Value).SingleOrDefault(a => a.MainDept_Id == addStudentViewModel.Department_Id);
                var Student = new Student { Dept_Id = department.Department_Id, Std_User_Id = userId };
                _studentRepo.Add(Student);
                var studentCourses = _departmentRepo.GetByBranchAndMainDepartment(branchId.Value, addStudentViewModel.Department_Id).Navigation_Courses.ToList();
                addStudentViewModel.StudentCourses = studentCourses;
                addStudentViewModel.Student_Id = Student.Student_Id;
                _studentRepo.AddRole(Student.Student_Id);
                return View("AddCourses", addStudentViewModel);
            }
            else
            {
                return View(addStudentViewModel);
            }
        }

        [HttpPost]
        public IActionResult AddCourses(int id,List<int> StudentCoursesId) {
            foreach(var item in StudentCoursesId)
            {
                _studentCourseRepo.Add(id,item);
            }
            return RedirectToAction("Index");
        }

        public IActionResult DisplayStudents(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            else
            {
                Course course = _courseRepo.GetById(id.Value);
                if (course == null)
                {
                    return NotFound();

ITIExaminationSyustem/Controllers/UserController.cs
using ITIExaminationSyustem.Interfaces;
using ITIExaminationSyustem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace ITIExaminationSyustem.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        IUserRepo _userRepo;
        IAdminRepo _adminRepo;
        IInstructorRepo _instructorRepo;
        IStudentRepo _studentRepo;

        public UserController(IUserRepo userRepo, IAdminRepo adminRepo, IInstructorRepo instructorRepo, IStudentRepo studentRepo)
        {
            _userRepo = userRepo;
            _adminRepo = adminRepo;
            _instructorRepo = instructorRepo;
            _studentRepo = studentRepo;
        }

        public IActionResult Index()
        {
            List<User> users = _userRepo.GetAll();
            _userRepo.GetNonAssignedUsers();
            return View(users);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            else
            {
                User fetchedUser = _userRepo.GetById(id.Value);
                if (fetchedUser == null)
                {
                    return NotFound();
                }
                else
                {
                    return View(fetchedUser);
                }
            }
        }

        public IActionResult UserDetails(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            else
            {
                User fetchedUser = _userRepo.GetById(id.Value);
                if (fetchedUser == null)
                {
                    return NotFound();
                }
                else
                {
                    return View(fetchedUser);
                }
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        async public Task<IActionResult> Create(User user, IFormFile image)
        {
            if(ModelState.IsValid)
            {
                _userRepo.Add(user);
                await _userRepo.AddImage(user, image);
                return RedirectToAction("Index");
            }
            else
            {
                return View(user);
            }
        }

        public IActionResult Edit(int? id)
        {
            if(id == null)
            {
                return BadRequest();
            }
            else
            {
                User userToEdit = _userRepo.GetById(id.Value);
                if(userToEdit == null) 
                { 
                    return NotFound();
                }
                else
                {
                    return View(userToEdit);
                }
            }
        }

        [HttpPost]
        async public Task<IActionResult> Edit(User user, int id, IFormFile image)
        {
            user.User_Id = id;
            if (ModelState.IsValid)
            {
                _userRepo.Update(user);
                await _userRepo.AddImage(user, image);
                return RedirectToAction("Index");
            }
            else
            {
                return View(user);
            }
        }

        public IActionResult Delete(int? id)
        {
            if(id == null)
            {
                return BadRequest();
            }
            else
            {
                User user = _userRepo.GetById(id.Value);
                if (user == null)
                {
                    return NotFound();
                }
                else
                {
                    if (user.Navigation_Instructor != null)
                        _instructorRepo.Delete(user.Navigation_Instructor.Instructor_Id);

                    else if (user.Navigation_Student != null)
                        _studentRepo.Delete(user.Navigation_Student.Student_Id);

                    else if (user.Navigation_Admin != null)
                        _adminRepo.Delete(user.Navigation_Admin.Admin_Id);

                    _userRepo.Delete(id.Value);
                    return RedirectToAction("Index");
                }
            }
        }
    }
}

ITIExaminationSyustem/Views/Student/Add.cshtml
@model List<Branch>
@{
    ViewBag.Title = "Add Student";
    SelectList Branches = new SelectList(Model, "Branch_Id", "Branch_Name");
    SelectList Users = new SelectList(ViewBag.Users, "User_Id", "User_Name");

}
<h4>Add a Student</h4>
<form >
    <label class="form-label mt-3 fw-bold" for="branchId">Branch</label>
    <select asp-items="Branches" class="form-select" name="branchId">
    </select>
    <label class="form-label mt-3 fw-bold" for="userId">user</label>
    <select asp-items="Users" class="form-select" name="userId">
    </select>
    <input type="submit" class="btn btn-dark mt-3" asp-action="AddToBranch" value="submit" />
</form>



@* <table>
    <thead>
        <th>Branch</th>
        <th>Operation</th>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.Branch_Name</td>
                <td><a class="btn btn-success" >Add Students to branch</a></td>
            </tr>
        }
    </tbody>
</table> *@

ITIExaminationSyustem/Views/Student/AddCourses.cshtml
@model AddStudentViewModel
@{
    ViewBag.Title = "Add Courses";
    SelectList CoursesList = new SelectList(Model.StudentCourses, "Course_Id", "Course_Name");
}

<form method="post" class="form-control">
    <select asp-items="CoursesList" multiple name="StudentCoursesId">

    </select>
    <input type="submit" class="btn btn-danger" asp-action="AddCourses" asp-route-id="@Model.Student_Id" value="submit" />
    <a >Submit Courses</a>
</form>

ITIExaminationSyustem/Views/Student/AddToBranch.cshtml
@model List<MainDepartment>
@{
    ViewBag.Title = "Add to Branch";
    SelectList mainDepartments = new SelectList(Model, "MainDepartment_Id", "MainDepartment_Name");

}
<form class="form-control" method="post">
    <select asp-items="mainDepartments" name="Department_Id">

    </select>
    @* <input type="number" name="User_Id" value="" placeholder="User Id" /> *@

    <input type="submit"  value="submit" />
</form>

ITIExaminationSyustem/Views/Student/Details.cshtml
@model Student
@{
    ViewBag.Title = "Student Details";
}
<h5 class="card-title">@ViewBag.Title</h5>



<table class="table table-striped table-hover"> 
    <tbody>
        <tr>
            <td class="fw-bold">Image</td>
            <td><img src="@Model.Navigation_User.User_Image" alt="Alternate Text" class="img-fluid" style="width:150px;height:150px" /></td>
        </tr>
        <tr> 
            <td class="fw-bold">Name</td>
            <td>@Model.Navigation_User.User_Name</td>
        </tr>
        <tr>
            <td class="fw-bold">Email</td>
            <td>@Model.Navigation_User.User_Email</td>
        </tr>
        <tr>
            <td class="fw-bold">Department</td>
            <td>@Model.Navigation_Department.Navigation_MainDepartment.MainDepartment_Name</td>
        </tr>
    </tbody>
</table>



<h2>Courses</h2>
<table class="table table-striped table-hover">
    <thead>
        <th>Course name</th>
        <th>Course duration</th>
        <th>Course Exam Date</th>
        <th>Course Grade</th>
        <th>Course Bouns</th>
    </thead>
    <tbody>
        @foreach (var item in Model.Navigation_StudentCourses)
        {
            <tr>
                <td>@item.Navigation_Course.Course_Name</td>
                <td>@item.Navigation_Course.Course_Duration</td>
                <td>@item.Navigation_Course.Course_Exam_StartDate</td>
                <td>@item.Grade</td>
                <td>@item.Bonus</td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="Index" asp-for="Student" class="btn btn-dark">Go Back</a>

ITIExaminationSyustem/Views/Student/DisplayStudents.cshtml
@model List<StudentCourse>
@{
    ViewData["Title"] = "DisplayStudents";
    List<Exam> allExams = ViewBag.ExamsList;
    Exam fetchedExam = null;
}

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Student name</th>
            <th>Email</th>
            <th>Grade</th>
            <th>Bonus</th>
            <th>Feedback</th>
            <th>Exam</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Navigation_Student.Navigation_User.User_Name</td>
                <td>@item.Navigation_Student.Navigation_User.User_Email</td>
                <td>@item.Grade</td>
                <td>@item.Bonus</td>
                <td>@item.Ins_Feedback</td>
                <td>
                    @{
                    fetchedExam = @allExams.Where(exam => exam.Crs_Id == item.Crs_Id && exam.StudId == item.Std_Id).LastOrDefault();
                    }
                    @if(fetchedExam == null)
                    {
                        <button class="btn btn-info" disabled >View Exam</button>
                        <button class="btn btn-info" disabled>View Exam Template</button>
                    }
                    else
                    {
                        <a asp-action="DisplayExamTemplate" asp-controller="Exam" asp-route-examId="@fetchedExam.Exam_Id" asp-route-isAnswered="@true" class="btn btn-info">View Exam</a>
                        <a asp-action="DisplayExamTemplate" asp-controller="Exam" asp-route-examId="@fetchedExam.Exam_Id" asp-route-isAnswered="@false" class="btn btn-info">View Exam Template</a>
                        fetchedExam = null;
                    }
                    
                </td>
            </tr>
        }
    </tbody>
</table>

ITIExaminationSyustem/Views/Student/Edit.cshtml
@model StudentDepartmentsViewModel
@{
    ViewBag.Title = "Edit Student";
    
    SelectList mainDepartments = new SelectList(Model.MainDepartmentsInStudentBranch, "MainDepartment_Id", "MainDepartment_Name");
    SelectList CoursesNotInStudent = new SelectList(ViewBag.CoursesNotInStudent, "Course_Id", "Course_Name");
    SelectList CoursesInStudent = new SelectList(Model.StudentCourses, "Course_Id", "Course_Name");
}



<form class="form-control" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="exampleFormControlInput1">Name</label>
        <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="Name" value="@Model.Student_Name" name="Student_Name">
    </div>

    <div class="form-group">
        <label for="studemail">Email</label>
        <input type="text" class="form-control" id="studemail" placeholder="Email" value="@Model.Student_Email" name="Student_Email">
    </div>

    <div class="form-group">
        <label for="studDep">Department</label>
        <select class="form-select" id="studDep" asp-items="mainDepartments" name="Student_DepartmentNumber">
            
        </select>
    </div>

    <div class="form-group">
        <label for="StdCrses"> Student Courses</label>
        <select multiple class="form-select" id="StdCrses" asp-items="CoursesInStudent" name="toRemove">
            
        </select>

        <label for="NotStdCrses"> Other Courses</label>
        <select multiple class="form-select" id="NotStdCrses" asp-items="CoursesNotInStudent" name="toAdd">
        </select>
    </div>

    <div class="form-group">
        <input type="file" class="form-control mt-3" name="image" />
    </div>

    <input type="submit" class="btn btn-dark mt-3" value="Update Student" />
   
</form>

ITIExaminationSyustem/Views/Student/Index.cshtml
@model List<Student>
@{
    ViewBag.Title = "Students";
}
<h1>Students</h1>
<table class="table table-hover table-striped ">

    <thead>
        <th>Student Id</th>
        <th>Student Name</th>
        <th>Student Email</th>
        <th>Department Name</th>
        <th>Operations</th>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.Student_Id</td>
                <td>@item.Navigation_User?.User_Name</td>
                <td>@item.Navigation_User?.User_Email</td>
                <td>@item.Navigation_Department?.Navigation_MainDepartment?.MainDepartment_Name</td>
                <td>
                    <a class="btn btn-dark" asp-action="Details" asp-for="Student" asp-route-id="@item.Student_Id">Details</a>|
                    <a class="btn btn-dark" asp-action="Edit" asp-for="Student" asp-route-id="@item.Student_Id">Edit</a>|
                    <a class="btn btn-danger" class="btn btn-danger" asp-action="Delete" asp-controller="User" asp-route-id="@item.Navigation_User.User_Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a class="btn btn-dark" asp-action="Add">Add Students</a>

ITIExaminationSyustem/Views/Student/StudentCourses.cshtml
@model Student
@{
    ViewData["Title"] = "StudentCourses";
    List<Exam> allExams = ViewBag.ExamsList;
    Exam fetchedExam = null;
    DateTime? deadLineDate = null;
}

<h1>Student Courses</h1>

<table class="table table-bordered table-hover">
    <thead>
    <th>Course name</th>
    <th>Course duration</th>
    <th>Course Exam Date</th>
    <th>Course Grade</th>
    <th>Course Bonus</th>
    </thead>
    <tbody>
        @foreach (var item in Model.Navigation_StudentCourses)
        {
            <tr>
                <td>@item.Navigation_Course.Course_Name</td>
                <td>@item.Navigation_Course.Course_Duration</td>
                <td>
                    @item.Navigation_Course.Course_Exam_StartDate

                    @{deadLineDate = @item.Navigation_Course.Course_Exam_StartDate.AddHours(1);}

                    @if ((DateTime.Now > @item.Navigation_Course.Course_Exam_StartDate) && (DateTime.Now < @deadLineDate) && (@item.HasTakenExam == false))
                    {
                        <a asp-action ="TakeExam" asp-controller="Exam" asp-route-stdId="@Model.Student_Id" asp-route-crsId="@item.Crs_Id" class="btn btn-danger TakeExamBtn">Take Exam</a>
                        fetchedExam = @allExams.Where(exam => exam.Crs_Id == item.Crs_Id && exam.StudId == item.Std_Id).LastOrDefault();
                        if(fetchedExam == null)
                        {
                            <button class="btn btn-info" disabled>View Exam</button>
                        }
                        else
                        {
                            if (@item.HasTakenExam == true)
                            {
                                <a asp-action="DisplayExamTemplate" asp-controller="Exam" asp-route-examId="@fetchedExam.Exam_Id" asp-route-isAnswered="@true" class="btn btn-info ViewExamBtn">View Exam</a>
                            }
                            else
                            {
                                <button class="btn btn-info" disabled>View Exam</button>
                            }
                            fetchedExam = null;
                        }
                    }
                    else
                    {
                        <button class="btn btn-danger" disabled>Take Exam</button>
                        fetchedExam = @allExams.Where(exam => exam.Crs_Id == item.Crs_Id && exam.StudId == item.Std_Id).LastOrDefault();
                        if (fetchedExam == null)
                        {
                            <button class="btn btn-info" disabled>View Exam</button>
                        }
                        else
                        {
                            if (@item.HasTakenExam == true)
                            {
                                <a asp-action="DisplayExamTemplate" asp-controller="Exam" asp-route-examId="@fetchedExam.Exam_Id" asp-route-isAnswered="@true" class="btn btn-info ViewExamBtn">View Exam</a>
                            }
                            else
                            {
                                <button class="btn btn-info" disabled>View Exam</button>
                            }
                            fetchedExam = null;
                        }
                    }
                    @{
                        deadLineDate = null;
                    }
                </td>
                <td>@item.Grade</td>
                <td>@item.Bonus</td>
            </tr>
        }
    </tbody>
</table>


@* @section Scripts {
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var takeExamButtons = document.querySelectorAll('.TakeExamBtn');
            var viewExamButtons = document.querySelectorAll('.ViewExamBtn');

            takeExamButtons.forEach(function (button) {
                var courseId = button.dataset.courseId;
                var hasTakenExam = button.dataset.hasTakenExam;
                var dateOfToday = new Date();
                var examStartingDate = new Date(button.dataset.examDate);
                var oneHour = 1 * 60 * 60 * 1000;
                var examDeadlineDate = new Date(examStartingDate.getTime() + oneHour);
                var isExamDatePassed = (dateOfToday > examStartingDate) && (dateOfToday < examDeadlineDate) && (hasTakenExam == "false");

                if (isExamDatePassed) {
                    button.disabled = false;
                }
            });

            viewExamButtons.forEach(function (button) {
                var hasTakenExam = button.dataset.hasTakenExam;

                var isEnabled = (hasTakenExam == "true");

                if (isEnabled) {
                    button.disabled = false;
                }
            });
        });
    </script>
}
 *@