ITIExaminationSyustem/Models/Branch.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ITIExaminationSyustem.Models
{
    public class Branch
    {
        [Key]
        public int Branch_Id { get; set; }
        public string  Branch_Name { get; set; }
        public string Branch_Manager_Name { get; set; }





        #region Navigation Property

        public ICollection<Department> Navigation_Departments { get; set; } = new HashSet<Department>();
        public Admin? Navigation_Admin { get; set; }

        #endregion
    }
}

ITIExaminationSyustem/Controllers/BranchController.cs
using ITIExaminationSyustem.Interfaces;
using ITIExaminationSyustem.Models;
using ITIExaminationSyustem.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ITIExaminationSyustem.Controllers
{
    [Authorize]
    public class BranchController : Controller
    {
        private IBranchRepo branchRepo;
        private IInstructorRepo instructorRepo;

        public BranchController(IBranchRepo branchRepo, IInstructorRepo instructorRepo)
        {
            this.branchRepo = branchRepo;
            this.instructorRepo = instructorRepo;
        }
        public IActionResult Index()
        {
            var branchList = branchRepo.GetAll();
            return View(branchList);
        }
        [HttpGet]
        public IActionResult AddBranch()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Save(Branch branch)
        {
            if(branch != null)
            {
                branchRepo.Add(branch);
                return RedirectToAction("Index");
            }
            return NotFound();
        }
        public IActionResult Delete(int? id)
        {
            if(id != null)
            {
                branchRepo.Delete(id.Value);
                return RedirectToAction("Index");
            }
            return BadRequest();
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return BadRequest();
            else
            {
                var branchToEdit = branchRepo.GetById(id.Value);
                if (branchToEdit == null)
                    return NotFound();
                else
                {
                    return View(branchToEdit);
                }
            }
            
        }
        [HttpPost]
        public IActionResult Update(Branch branch)
        {
            if(branch != null)
            {
                branchRepo.Update(branch);
                return RedirectToAction("Index");
            }
            return BadRequest();
            
        }
        public IActionResult Details(int? id)
        {
            if(id != null)
            {
                var targetBranch = branchRepo.GetById(id.Value);
                return View(targetBranch);
            }
            return NotFound();
        }
    }
}

ITIExaminationSyustem/Views/Branch/AddBranch.cshtml
@model Branch
@{
    ViewData["Title"] = "AddBranch";
}

<h1>Add Branch Details</h1>

<form asp-action="Save" asp-controller="Branch" method="post">
    <div class="form-group">
        <label asp-for="@Model.Branch_Name"></label>
        <input asp-for ="@Model.Branch_Name" type="text" class="form-control" placeholder="Enter Branch Name">
    </div>
    <div class="form-group">
        <label asp-for="@Model.Branch_Manager_Name"></label>
        <input asp-for="@Model.Branch_Manager_Name" type="text" class="form-control" placeholder="Enter Manager Name">
    </div>
    <input type="submit" value="save" class="btn btn-danger" />
</form>

<a asp-action="Index" asp-controller="Branch" class="btn btn-dark mt-3">Back To List</a>

ITIExaminationSyustem/Views/Branch/Details.cshtml
@model Branch
@{
    ViewData["Title"] = "Details";
}

<h1>Branch Details</h1>

<table class=" table table-striped table-hover">
    <thead>
        <tr>
            <th>Branch Name</th>
            <th>Branch Manager</th>
            <th>Branch Admin</th>
            <th>Branch Department</th>
            <th>Branch Student Numbers</th>
        </tr>
    </thead>

    <tbody>
        <tr>
             <td>@Model.Branch_Name</td>
             <td>@Model.Branch_Manager_Name</td>
        </tr>
    </tbody>
    </table>
<a asp-action="Index" asp-controller="Branch" class="btn btn-dark mt-3">Back To List</a>

ITIExaminationSyustem/Views/Branch/Edit.cshtml
@model Branch
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Branch</h1>

<form asp-action="Update" asp-controller="Branch" method="post">
    <input type="hidden" asp-for="@Model.Branch_Id" />
    <div class="form-group">
        <label asp-for="@Model.Branch_Name"></label>
        <input asp-for="@Model.Branch_Name" type="text" class="form-control" placeholder="Enter Branch Name">
    </div>
    <div class="form-group">
        <label asp-for="@Model.Branch_Manager_Name"></label>
        <input asp-for="@Model.Branch_Manager_Name" type="text" class="form-control" placeholder="Enter Manager Name">
    </div>
    <input type="submit" value="Update" class="btn btn-danger mt-2" />
</form>

<a asp-action="Index" asp-controller="Branch" class="btn btn-dark mt-3">Back To List</a>

ITIExaminationSyustem/Views/Branch/Index.cshtml
@model IEnumerable<Branch>
@{
    ViewData["Title"] = "Index";
}

<h1>Branches Details</h1>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th>Branch name</th>
            <th>Branch Manager</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.Branch_Name</td>
                <td>@item.Branch_Manager_Name</td>
                <td>
                    <a asp-action="Details" asp-controller="Branch" asp-route-Id="@item.Branch_Id" class="btn btn-dark">Details</a>
                    <a asp-action="Edit" asp-controller="Branch" asp-route-Id="@item.Branch_Id" class="btn btn-dark">Edit</a>
                    <a asp-action="Delete" asp-controller="Branch" asp-route-Id="@item.Branch_Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    
    </tbody>
</table>
<a asp-action="AddBranch" asp-controller="Branch" class="btn btn-dark mt-3">Add a branch</a>